#' Run the Full Analysis Pipeline for a Specific Tissue
#'
#' This function assigns cell types using an OpenAI GPT model, computes weighted average distances,
#' and calculates p-values based on a gamma distribution from a bootstrap. The appropriate tree, distance matrix,
#' and gamma parameters (shape and rate) are selected automatically based on the tissue type.
#'
#' @param cell_type_lists A list or matrix of predicted cell type lists generated by the CT_GPTpredict.
#' @param tissue A character string specifying the tissue type ("PBMC", "Heart", "Lung", or "Kidney").
#' @param model The GPT model to use (default is 'gpt-4').
#' @return A list containing the p-values.
#' @export
#' @examples
#' data(list = c("heart_df","heart_distance_mtx","kidney_df","kidney_distance_mtx","lung_df","lung_distance_mtx","pbmc_df","pbmc_distance_mtx",
#' "brain_df","brain_distance_mtx_na","breast_df","breast_distance_mtx_na","liver_df","liver_distance_mtx_na","marker_PBMC"),package = "Tapas")
#' predict_res<-CT_predict(N=3,marker= marker_PBMC, tissueName='PBMC', model='gpt-4',provider='gpt') 
#' p_res<-tapas_pipeline(predict_res,N=3,tissue="PBMC")
#' p_res


tapas_pipeline <- function(cell_type_lists,
                           model = 'gpt-4', tissue = c("PBMC", "Heart", "Lung", "Kidney","Brain","Breast","Liver")) {
  # Ensure a valid tissue is provided
  tissue <- match.arg(tissue)
  
  # Lookup table: for each tissue, specify the gamma parameters and corresponding data objects.
  params <- list(
    PBMC = list(
      shape    = 1.9278,  
      rate     = 0.0960,
      tree     = pbmc_df,          
      distance = pbmc_dis_mtx_na     
    ),
    Heart = list(
      shape    = 2.582543, 
      rate     = 0.1354775,
      tree     = heart_df,         
      distance = heart_distance_mtx    
    ),
    Lung = list(
      shape    = 3.10023,  
      rate     = 0.161203,
      tree     = lung_df,          
      distance = lung_dis_mtx_na      
    ),
    Kidney = list(
      shape    = 3.008188, 
      rate     = 0.1486833,
      tree     = kidney_df,        
      distance = kidney_dis_mtx_na    
    ),
    Brain = list(
      shape    = 1.9258,  
      rate     = 0.0829,
      tree     = brain_df,          
      distance = brain_distance_mtx_na      
    ),
    Breast = list(
      shape    = 2.5789,  
      rate     = 0.13225,
      tree     = breast_df,          
      distance = breast_distance_mtx_na      
    ),
    Liver = list(
      shape    = 2.49427,  
      rate     = 0.14472,
      tree     = liver_df,          
      distance = liver_distance_mtx_na      
    )
  )
  
  # Extract the shape and rate for the selected tissue
  tissue_params <- params[[tissue]]
  tree_df     <- tissue_params$tree
  distance_mtx <- tissue_params$distance
  shape       <- tissue_params$shape
  rate        <- tissue_params$rate
  N <- ncol(cell_type_lists)
  
  # Step 1: Assign cell types for each cell type list
  frequency_table_list <- apply(cell_type_lists, 1, table)
  assigned_results <- Assign_Multiple_Cell_Types(frequency_table_list, tree_df, model)
  
  # Step 2: Compute the weighted average distances
  avg_distance <- Get_avg_dis(assigned_results, frequency_table_list, distance_mtx, N=N)
  
  # Step 3: Calculate p-values for each average distance using the gamma distribution.
  p_values <- get_p_vector(avg_distance, shape, rate)
  
  return(p_values)
}
